use std::fmt::Debug;

use crate::{difficulty_bytes_as_u128, u128_bytes, u32_bytes, u64_bytes, Hashable};

use super::BlockHash;

pub struct Block {
    pub index: u32,
    pub nonce: u64,
    pub timestamp: u128,
    pub payload: String,
    pub block_hash: BlockHash,
    pub prev_block_hash: BlockHash,
    pub difficulty: u128,
}

impl Debug for Block {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "\nBlock[{}]: \nBlock Hash: {} \ntimestamp: {} \npayload: {} \nnonce: {} \nPrevious Block Hash: {} \n",
            &self.index,
            &hex::encode(&self.block_hash),
            &self.timestamp,
            &self.payload,
            &self.nonce,
            &hex::encode(&self.prev_block_hash),
        )
    }
}

// this has a fn to create blocks
impl Block {
    pub fn create_new_block(
        index: u32,
        nonce: u64,
        timestamp: u128,
        payload: String,
        prev_block_hash: BlockHash,
        difficulty: u128,
    ) -> Self {
        Self {
            index,
            nonce,
            timestamp,
            payload,
            prev_block_hash,
            block_hash: vec![0; 32],
            difficulty,
        }
    }

    pub fn mine(&mut self) {
        // increment from 0 to u64 max value then append the nonce in our block then hash the block
        for nonce_incrementor in 0..(u64::max_value()) {
            self.nonce = nonce_incrementor;
            let hash = self.hash();
            // covert the hash vector to to u128 bytes integer
            let hash_byte = difficulty_bytes_as_u128(&hash);
            // now check if the size of difficulty byte is greater than hash_byte size or not
            // TODO: try increasing and decreasing the number of zereos of difficulty parameter.
            if is_difficulty_met(hash_byte, self.difficulty) {
                // set the block hash that met the condition
                self.block_hash = hash;
                return;
            }
        }
    }
}

impl Hashable for Block {
    fn block_to_bytes(&self) -> Vec<u8> {
        let mut bytes: Vec<u8> = vec![];

        // convert index which is u32 to an array of u8 values and extending that to bytes variable
        bytes.extend(&u32_bytes(&self.index));
        // convert nonce (u64) to array of u8
        bytes.extend(&u64_bytes(&self.nonce));
        // convert timestamp (u128) to array of u8
        bytes.extend(&u128_bytes(&self.timestamp));
        // convert payload to byte
        bytes.extend(self.payload.as_bytes());
        bytes.extend(&self.prev_block_hash);

        bytes
    }
}
// this is our criteria for mining
// if  difficulty (0x0000ffffffffffffffffffffffffffff) is greater than hash_byte,
// for example if hash_byte generated by incrementing the nonce and hashing the block then coverting it to u128 integer
// comes out to be 0x0000f0fffeeffffefff4fffefffe0ffff we have met the criteria,
// where 0x0000ffffffffffffffffffffffffffff is simply greater than 0x0000f0fffeeffffefff4fffefffe0ffff
pub fn is_difficulty_met(hash_byte: u128, difficulty: u128) -> bool {
    difficulty > hash_byte
}
